<?php

use Illuminate\Database\Seeder;

class PagesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('pages')->insert([
            'title' => 'home',
            'data' => '{"ourProducts": "Chute Help’s automatic roping chute products are easily installed and do not require electricity or an air compression system in the roping arena.", "learnAboutUs": "Made in Texas, Chute Help continues to improve and design new roping arena accessories that will improve facility efficiency and operation.", "findARetailer": "Can’t find an authorized Chute Help retailer near you? Search for retailers with our location tool.", "highlight1title": "Chute Help Fully Automatic Roping Chute", "highlight2title": "Chute Help Full Arena Setup", "highlight3title": "Chute Help Easy Exit Stripping Chute", "siteDescription": "Chute Help, Inc. has manufactured innovative roping chutes, arena accessories, and horse training products for the past six years, and continues to be committed to improving and designing high-quality roping chutes and accessories, and bettering the Western industry.", "highlight1youtube": "https://www.youtube.com/embed/86kig1AOvTQ", "highlight2youtube": "https://www.youtube.com/embed/B-RLktuDj-o", "highlight3youtube": "https://www.youtube.com/embed/XDRyqYBK4aA", "highlight1learnMore": "#", "highlight2learnMore": "#", "highlight3learnMore": "#", "productFeature1title": "Chute Help Pivoting Adjustable Roping Boxes", "productFeature2title": "Chute Help Lead Ups", "productFeature3title": "Chute Help Open Sweep", "highlight1description": "The Chute Help Farm Gate is the perfect way to stay stylish, while being functional. The Chute Help Farm Gate is the perfect way to stay stylish. The Chute Help Farm Gate is the perfect way to stay stylish, while being functional. The Chute Help Farm Gate is the perfect way to stay stylish.", "highlight2description": "Chute Help\'s lead ups are all equipped with dual alley stops, making sorting and loading simple. The dual alley stops make the steer\'s transition from one section to the next smooth and steady. Chute Help\'s lead ups are all equipped with dual alley stops, making sorting and loading simple. The dual alley stops make the steer\'s transition from one section to the next smooth and steady.", "highlight3description": "The Chute Help Farm Gate is the perfect way to stay stylish, while being functional. The Chute Help Farm Gate is the perfect way to stay stylish. The Chute Help Farm Gate is the perfect way to stay stylish, while being functional. The Chute Help Farm Gate is the perfect way to stay stylish.", "productFeature1description": "Some quick example text to build on the card title and make up the bulk of the card\'s content.", "productFeature2description": "Some quick example text to build on the card title and make up the bulk of the card\'s content.", "productFeature3description": "Some quick example text to build on the card title and make up the bulk of the card\'s content.", "productFeature1storePageUrl": "#", "productFeature2storePageUrl": "#", "productFeature3storePageUrl": "#"}',
            'assets' => '{"productFeatureImage1": "/img/default/product-feature-1-resized.jpg", "productFeatureImage2": "/img/default/product-feature-2-resized.jpg", "productFeatureImage3": "/img/default/product-feature-3-resized.jpg"}'
        ]);

        DB::table('pages')->insert([
            'title' => 'contact',
            'data' => '{"emailHelper": "Get notified when we add new products", "addressField": "500 S. Main St., Carbon, TX 76435", "contactHeader": "We\'d love to hear from you", "sectionHeader": "CHUTE HELP, INC. HAS MANUFACTURED INNOVATIVE ROPING CHUTES, ARENA ACCESSORIES AND HORSE TRAINING PRODUCTS FOR THE PAST SIX YEARS, AND CONTINUES TO BE COMMITTED TO IMPROVING AND DESIGNING HIGH-QUALITY ROPING CHUTES AND ACCESSORIES, AND BETTERING THE WESTERN INDUSTRY.", "phoneNumberField": "1-855-CHUTEHELP (248-8343)", "emailAddressField": "info@chutehelp.com", "sectionParagraph1": "Chute Help\'s roping arena products are easily installed, and allow everyone to have a fully automatic roping chute without having to install electricity or an air compression system in their roping arena.", "sectionParagraph2": "The Chute Help Fully Automatic Roping Chute\'s (US Patent 7,918,191; Canadian Patent ...) front gate remote-release portion is not what makes it innovative. However, when the front gate closes after the steer exits the roping chute, the rear gate opens automatically. The rear gate of the roping chute then closes behind the steer after it enters. The back gate latch mechanism keeps the steer from backing up in the roping chute. The energy to operate this simple mechanism is created by the animal entering the roping chute and depressing a platform, in the floor, down four inches. Our roping chute is very easy on livestock and requires less manual labor. The Chute Help Fully Automatic Roping Chute can be placed virtually anywhere and still maintain the convenience of a remote release roping chute. This product has been tested for six years and has had thousands of cycles.", "sectionDescription": "Originating in Northern Colorado, Chute Help, Inc. continues to be a family owned and operated company, that currently operates and manufactures in Carbon, Texas.", "contactCardDescription": "From ordering a Chute Help automatic roping chute, to support, or just saying hello to check on new products, we want to hear from you. Feel free to call or email us and we’ll get back to you as soon as possible!", "sectionVideoYouTubeURL": "https://www.youtube.com/embed/XgebBDI3oGQ"}',
            'assets' => '{}'
        ]);
    }
}